# Generated by Django 3.2.5 on 2021-08-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=10)),
                ('enrollmentno', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='workshopdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Details', models.TextField()),
                ('LastRegisterDate', models.DateTimeField(blank=True)),
                ('NoofPeopleRegistered', models.IntegerField(default=0)),
                ('attendee1', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.attendee')),
            ],
        ),
        migrations.DeleteModel(
            name='attend',
        ),
    ]
