# Generated by Django 3.2.5 on 2021-08-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_auto_20210815_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdetails',
            name='currentuserattending',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='workshopdetails',
            name='attendee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.attendee'),
        ),
    ]
